services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservicos-net

  config-server:
    build: ./config-server
    container_name: config-server
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///config-repo
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8888/produtos-service/docker > /dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 15s
    networks:
      - microservicos-net

  produtos-service:
    build: ./produtos-service
    container_name: produtos-service
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservicos-net

  vendas-service:
    build: ./vendas-service
    container_name: vendas-service
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservicos-net
  
  clientes-service:
    build: ./clientes-service
    container_name: clientes-service
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservicos-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservicos-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8085:8085"
    networks:
      - microservicos-net

networks:
  microservicos-net:
    driver: bridge
